"""baseline trading schema

Revision ID: 7dbbacfd8728
Revises: 
Create Date: 2026-07-29 09:25:08.586643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dbbacfd8728'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('position_slots', sa.Integer(), nullable=False),
    sa.Column('volume_multiplier', sa.Float(), nullable=False),
    sa.Column('concentration_slope', sa.Float(), nullable=False),
    sa.Column('atr_multiplier', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STOPPED', name='strategystatus'), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_name'), 'strategy', ['name'], unique=False)
    op.create_index(op.f('ix_strategy_status'), 'strategy', ['status'], unique=False)
    op.create_table('order_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='orderaction'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'FILLED', 'CANCELLED', 'FAILED', 'TIMEOUT', name='orderstatus'), nullable=False),
    sa.Column('sell_reason', sa.Enum('TRAILING_STOP', 'SIGNAL_EXIT', 'MANUAL', name='sellreason'), nullable=True),
    sa.Column('req_quantity', sa.Integer(), nullable=False),
    sa.Column('req_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('filled_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('return_rate', sa.Float(), nullable=False),
    sa.Column('error_msg', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_record_broker_order_id'), 'order_record', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_order_record_create_at'), 'order_record', ['create_at'], unique=False)
    op.create_index(op.f('ix_order_record_status'), 'order_record', ['status'], unique=False)
    op.create_index(op.f('ix_order_record_strategy_id'), 'order_record', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_order_record_symbol'), 'order_record', ['symbol'], unique=False)
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('highest_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('trailing_stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('create_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_create_at'), 'position', ['create_at'], unique=False)
    op.create_index(op.f('ix_position_strategy_id'), 'position', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_position_symbol'), 'position', ['symbol'], unique=False)
    op.create_table('strategy_daily_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('SIGNAL_GENERATED', 'EXECUTING', 'FINALIZING', 'ENDED', name='dailylogstatus'), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('execute_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_equity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('holdings_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('buy_signals_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sell_signals_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'record_date', name='uq_strategy_daily_log_date')
    )
    op.create_index(op.f('ix_strategy_daily_log_record_date'), 'strategy_daily_log', ['record_date'], unique=False)
    op.create_index(op.f('ix_strategy_daily_log_status'), 'strategy_daily_log', ['status'], unique=False)
    op.create_index(op.f('ix_strategy_daily_log_strategy_id'), 'strategy_daily_log', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_daily_log_strategy_id'), table_name='strategy_daily_log')
    op.drop_index(op.f('ix_strategy_daily_log_status'), table_name='strategy_daily_log')
    op.drop_index(op.f('ix_strategy_daily_log_record_date'), table_name='strategy_daily_log')
    op.drop_table('strategy_daily_log')
    op.drop_index(op.f('ix_position_symbol'), table_name='position')
    op.drop_index(op.f('ix_position_strategy_id'), table_name='position')
    op.drop_index(op.f('ix_position_create_at'), table_name='position')
    op.drop_table('position')
    op.drop_index(op.f('ix_order_record_symbol'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_strategy_id'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_status'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_create_at'), table_name='order_record')
    op.drop_index(op.f('ix_order_record_broker_order_id'), table_name='order_record')
    op.drop_table('order_record')
    op.drop_index(op.f('ix_strategy_status'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_name'), table_name='strategy')
    op.drop_table('strategy')
    # ### end Alembic commands ###
